export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_OK = "AUTH_LOGIN_OK";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";
export const AUTH_USER_ME = "AUTH_USER_ME";

export const USERS_LOAD = "USERS_LOAD";
export const USERS_LOAD_OK = "USERS_LOAD_OK";
export const USERS_LOAD_ERROR = "USERS_LOAD_ERROR";

export const USERS_REGISTER_LOGIN = "USERS_REGISTER_LOGIN";
export const USERS_REGISTER_LOGIN_OK = "USERS_REGISTER_LOGIN_OK";
export const USERS_REGISTER_LOGIN_ERROR = "USERS_REGISTER_LOGIN_ERROR";
